apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: kuberdemo
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: root1234
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kuberdemo-config
data:
  DATABASE_URL: r2dbc:postgresql://postgres-service/kuberdemo
  DATABASE_USER: postgres
  DATABASE_PASSWORD: root1234
