apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: kuberdemo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kuberdemo-config
data:
  DATABASE_URL: r2dbc:postgresql://postgres-service/kuberdemo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dbinit-config-file
data:
  db_init.sql: {{tpl (.Files.Get "files/db_init.sql") . | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dbinit-config
data:
  POSTGRES_DB: kuberdemo



