apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: kuberdemo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kuberdemo-config
data:
  DATABASE_URL: r2dbc:postgresql://postgres-service/kuberdemo

