apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
stringData:
  DATABASE_USER: postgres
  DATABASE_PASSWORD: root1234
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: root1234