apiVersion: v1
kind: Service
metadata:
  name: kuberdemo-service
spec:
  type: ClusterIP
  selector:
    app: {{.Chart.Name}}-backend
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8091
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  ports:
   - port: 5432    
  targetPort: 5432
  selector:
   app: {{.Chart.Name}}-db