apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Chart.Name}}-db
  labels:
    app: {{.Chart.Name}}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Chart.Name}}-db
  template:
    metadata:
      labels:
        app: {{.Chart.Name}}-db
    spec:
      containers:
        - name: kuberdemo-db
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: db-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
